---
version: '3'
services:
  quartermaster:
    image: "${USERNAME}/${IMAGE}:${VERSION}"
    container_name: quartermaster
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp

  quartermaster-ubuntu:
    image: "${USERNAME}/${IMAGE}-ubuntu:${VERSION}"
    container_name: quartermaster
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp


#  quartermaster-debian:
#    image: "${USERNAME}/${IMAGE}-debian:${VERSION}"
#    container_name: quartermaster
#    build:
#      context: .
#      dockerfile: Dockerfile.debian
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    tmpfs:
#      - /run
#      - /tmp

  quartermaster-centos:
    image: "${USERNAME}/${IMAGE}-centos:${VERSION}"
    container_name: quartermaster
    build:
      context: .
      dockerfile: Dockerfile.centos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp

